package com.example.mobile_moviescatalog2023.ui.theme

const val regOrLogScreen = "reg_or_log_screen"
const val registrationScreen = "registration_screen"
const val loginScreen = "login_screen"
const val registrationPasswordScreen = "registration_password_screen"
const val mainScreen = "main_screen"
const val favouritesScreen = "favourites_screen"
const val profileScreen = "profile_screen"
const val descriptionScreen = "movie_description_screen"
const val splashScr = "splash_screen"
const val isBack = "is_back"
const val loginExistsError = "Пользователь с таким логином уже существует."
const val passwordLengthError = "Длина пароля должна составлять не менее 6 символов."
const val wrongLoginError = "Неверный логин или пароль."
const val noConnectionError = "Нет подключения к сети."
const val emailValidationError = "Email введён некорректно."
